[package]
name = "henri-server"
version = "0.1.0"
authors = ["Henri E. Francois <henrifrancois97@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
reqwest = "0.9.5"
serde = "1.0.84"
serde_derive = "1.0.84"
error-chain = "0.12"